### PR TITLE
use yasm/ld from PATH

### PR DESCRIPTION
**Pull request by marler8997**
Use `yasm` and `ld` from `PATH`.

### CODE REVIEW

**Comment by mustafaquraish** [comment]
You might want to look at this commit I just pushed: 94867c898ea5f6c582b05d25abf958aec3003b7d

You can now access `envp` (on both macOS and Linux):

```rust
import "std/common.cup"

fn main(argc: int, argv: char**, envp: char**) {
    let e = envp;
    while (*e) {
        putsln(*e);
        ++e;
    }
}
```

**Comment by marler8997** [comment]
Looks like I get a segfault when I try to use `fn main(argc: int, argv: char **, envp: char **): int` on linux.

EDIT: problem might be that I'm using the old boostrap compiler and it wasn't updated?

**Comment by marler8997** [comment]
@mustafaquraish can you update the boostrap assembly so I can use the new `envp`?

**Comment by mustafaquraish** [comment]
> Looks like I get a segfault when I try to use `fn main(argc: int, argv: char **, envp: char **): int` on linux.
> 
> EDIT: problem might be that I'm using the old boostrap compiler and it wasn't updated?

Perhaps I should add an example to the README for workflow. Here's how I go about developing:

```bash
# Generate the bootstrap compiler and `build/cupcc` from current source
$ ./meta/bootstrap.sh
# Use `build/cupcc` to actually compile programs you are writing
$ ./build/cupcc examples/test.cup
# If you're modifying the compiler itself, it's helpful to use a level of indirection so `build/cupcc` is never corrupted
$ ./build/cupcc compiler/main.cup -r examples/testing_new_feature.cup
```

Doing it this way means I don't have to update the bootstrap compiler files with *every* new change, but only when the compiler is using the new features added. That's nice because the bootstrap files are relatively big, and git doesn't like big files.

> @mustafaquraish can you update the boostrap assembly so I can use the new `envp`?

If you follow the workflow above you should be able to use `envp`. I don't need to update the bootstrap yet because the compiler in the current tree does not itself use `envp`

**Comment by marler8997** [comment]
> If you follow the workflow above you should be able to use envp. I don't need to update the bootstrap yet because the compiler in the current tree does not itself use envp

Right, but weren't you suggesting I using `envp` in the compiler?

**Comment by mustafaquraish** [comment]
> > If you follow the workflow above you should be able to use envp. I don't need to update the bootstrap yet because the compiler in the current tree does not itself use envp
> 
> Right, but weren't you suggesting I using `envp` in the compiler?

Right, but we'd need to update the bootstrap files _after_ you have made the compiler use `envp`. It's a bit mind-bendy to think about 😅

**Comment by marler8997** [comment]
Hmmm, `execve` failing on macos now since I added passing `envp` to `execve`.  Looks like there is some weirdness around `execve` on macos but I don't really have a macos.

But we need to pass `execve` to subprocesses because of the recursive bootstrap test where the compiler calls itself multiple times, we need to propagate the `PATH` environment variable down each time.

I could workaround this at least temporarily by not passing `envp` down to the subprocess and then setting `PATH` to some default like `/bin:/usr/bin:/usr/local/bin` when it doesn't exist, or I think I'll need to wait for you to fix the macos issue since I don't have one.

**Comment by mustafaquraish** [comment]
> Hmmm, `execve` failing on macos now since I added passing `envp` to `execve`. Looks like there is some weirdness around `execve` on macos but I don't really have a macos.
> 
> But we need to pass `execve` to subprocesses because of the recursive bootstrap test where the compiler calls itself multiple times, we need to propagate the `PATH` environment variable down each time.
> 
> I could workaround this at least temporarily by not passing `envp` down to the subprocess and then setting `PATH` to some default like `/bin:/usr/bin:/usr/local/bin` when it doesn't exist, or I think I'll need to wait for you to fix the macos issue since I don't have one.

I did some investigating, and it seems that it's a macOS issue. Apparently the `syscall`s in assembly don't exactly mirror the linux counterparts (and seem to not actually be public facing APIs). Long story short, the `open` syscall doesn't return a negative value in `rax` on failing, (and so doesn't get passed as the return value), but in a separate register (or flag, I don't know which). Seems like a bit of a fundamental issue on how syscalls are handled at the moment, and I might need to re-think if it's even viable to support macOS given this.

I'm not exactly sure what the best solution is given this, but perhaps we can just do the PATH lookup for linux, and have the hardcoded path to the `yasm` executable for macos for now, until we have some better ideas.

**Comment by mustafaquraish** [comment]
I'm assuming you don't have macOS for testing. I'll have a closer look at the code when I get some time tomorrow and let you know how to fix it so you don't have to keep force-pushing and straining the CI. In the meantime it seems that you have it working locally, so you can work on something else if you'd like!

I'm probably going to have to do a bit of a major refactor on how the syscalls and multiple platforms are handled soon anyway, everything is a bit naive right now.

**Comment by marler8997** [comment]
@mustafaquraish actually it looks like it may not have been execve. I realized it was resolving `yasm` and `ld` to binaries underneath `/usr/local/lib/ruby/gems/2.7.0/bin` which weren't working.  So for now I just disabled the `which` lookup on macos to make the CI happy.

**Comment by marler8997** [comment]
Hmm, actually, my guess is this could be a problem on macos with using `open` to check if a file exists.  That would cause it to find `yasm` and/or `ld` in the first directory in `PATH`.

**Comment by mustafaquraish** [comment]
> Hmm, actually, my guess is this could be a problem on macos with using `open` to check if a file exists. That would cause it to find `yasm` and/or `ld` in the first directory in `PATH`.

Indeed. Please refer to my comment above: https://github.com/mustafaquraish/cup/pull/3#issuecomment-1043541999

**Comment by marler8997** [comment]
As I understand macos doesn't maintain a stable API for performing syscalls directly (unlike linux).  Instead they provide libSystem as their stable API layer which also contains an implementation of libc.

**Comment by mustafaquraish** [comment]
> As I understand macos doesn't maintain a stable API for performing syscalls directly (unlike linux). Instead they provide libSystem as their stable API layer which also contains an implementation of libc.

I think your original idea of using `/usr/bin/env` was the way to go. I've made some modifications that allows this to work directly to avoid duplicating the logic. This seems a bit too hacky with the several different checks and handling of separate platforms for me for right now, so I'm going to close it since it's no longer required. Once we have better handling of syscall errors consistently, perhaps we can do this properly in the stdlib.

**Comment by marler8997** [comment]
I would say this solution is a step forward from my `/usr/bin/env` solution as it properly implements the logic to find executables instead of relying on another tool.  I don't see much point in going backwards when we already have an implementation that works.

**Pull request closed without merging**
