### PR TITLE
Reimplemented `malloc(size)`, added `free(ptr*)` and `realloc(ptr*, size)`

### PR DESCRIPTION
**Pull request by Weltspear**

### CODE REVIEW

**Comment by mustafaquraish** [comment]
Thanks for this, some nice improvements! Just some things that would be nice to fix before merging this:

(1) Please check your line endings, use only `\n` instead of a carriage return. Your code editor should be able to do this, and it will make the diff much cleaner instead of showing the whole file as changed.

(2) Please squash all your commits. I'd prefer to not have a commit implementing a feature and then immediately have 2 commits after it modifying something trivial.

(3) Since there's a lot of extra code for the allocation stuff, let's move all the relevant things to something like `std/alloc.cup` and have it be included by `std/common.cup`, just to keep the logic separate.

**Comment by Weltspear** [comment]
(1) Okay 
(2) Do I have to "recommit" my commits to squash commits? 
(3) Okay

**Comment by mustafaquraish** [comment]
> Do I have to "recommit" my commits to squash commits?

If you're unsure how to squash your commits, I can do it for you, but for reference, here's a video that you might find helpful: https://www.youtube.com/watch?v=V5KrD7CmO4o

**Comment by Weltspear** [comment]
Okay, thank you.

**Comment by Weltspear** [comment]
I have moved memory related stuff (`malloc` etc. and `memcpy`) to `memory.cup`.

**Comment by mustafaquraish** [comment]
Thanks for working on this!

**Pull request merged**
